name: Lint, Build and Deploy

permissions:
    contents: read
    packages: write

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    cache: 'npm'

            -   name: Install dependencies
                run: npm ci

            -   name: Lint
                run: npm run lint

            -   name: Build
                if: success()
                run: npm run build --configuration=production

            -   name: Set up Docker Buildx
                if: success() && github.event_name != 'pull_request'
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Container Registry
                if: success() && github.event_name != 'pull_request'
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Generate image tag with timestamp
                if: success() && github.event_name != 'pull_request'
                id: meta
                run: echo "tag=$(date -u +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"

            -   name: Build and Push Docker Image
                if: success() && github.event_name != 'pull_request'
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: |
                        ghcr.io/${{ github.repository_owner }}/personal_website:latest
                        ghcr.io/${{ github.repository_owner }}/personal_website:${{ steps.meta.outputs.tag }}
