name: Release

on:
  push:
    branches: ['master']

jobs:
  release:
    name: 'Build docker image and push'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions: write-all
    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v4

      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 20

      - run: npm i -g pnpm
        name: Install pnpm

      - run: pnpm install
        name: Install dependencies

      - run: pnpm lint
        name: Run lint

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build the Docker image'
        run: docker build . --tag ghcr.io/simon-b64/personal_website:${{ steps.version-bump.outputs.newTag }} --tag ghcr.io/simon-b64/personal_website:latest

      - name: 'Push image to registry'
        run: docker push ghcr.io/simon-b64/personal_website --all-tags
